[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
morpho_clone = "AVS1hieS2uEKeCCmoJgCG7DS28dpiz7F71qovBwBNV9j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
