[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
morpho_clone = "AVS1hieS2uEKeCCmoJgCG7DS28dpiz7F71qovBwBNV9j"

[programs.devnet]
morpho_clone = "AVS1hieS2uEKeCCmoJgCG7DS28dpiz7F71qovBwBNV9j"

[programs.mainnet]
morpho_clone = "AVS1hieS2uEKeCCmoJgCG7DS28dpiz7F71qovBwBNV9j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
deploy = "anchor build && solana program deploy ./target/deploy/morpho_clone.so --with-compute-unit-price 100000"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
